/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.48
 * Generated at: 2025-12-01 08:36:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1764563398446L));
    _jspx_dependants.put("jar:file:/C:/Users/LENOVO/Desktop/Smart%20Student%20Feedback/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SmartFeedbackDashboard/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602854172000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Smart Student Feedback System</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        /* PROFESSIONAL DARK MAUVE THEME */\r\n");
      out.write("        :root {\r\n");
      out.write("            /* Mauve Color Palette */\r\n");
      out.write("            --mauve-dark: #6D4C5C;\r\n");
      out.write("            --mauve-medium: #8B6B7E;\r\n");
      out.write("            --mauve-light: #A993A1;\r\n");
      out.write("            --mauve-soft: #D1C2C9;\r\n");
      out.write("            --mauve-pastel: #E8DFE3;\r\n");
      out.write("            \r\n");
      out.write("            /* Accent Colors */\r\n");
      out.write("            --accent-gold: #C9A959;\r\n");
      out.write("            --accent-sage: #8A9A5B;\r\n");
      out.write("            --accent-slate: #708090;\r\n");
      out.write("            --accent-burgundy: #800020;\r\n");
      out.write("            \r\n");
      out.write("            /* Neutrals */\r\n");
      out.write("            --bg-light: #F8F6F7;\r\n");
      out.write("            --bg-white: #FFFFFF;\r\n");
      out.write("            --text-dark: #2D2D2D;\r\n");
      out.write("            --text-medium: #5A5A5A;\r\n");
      out.write("            --text-light: #FFFFFF;\r\n");
      out.write("            \r\n");
      out.write("            /* Gradients */\r\n");
      out.write("            --gradient-mauve: linear-gradient(135deg, var(--mauve-dark) 0%, var(--mauve-medium) 100%);\r\n");
      out.write("            --gradient-gold: linear-gradient(135deg, var(--accent-gold) 0%, #D4B483 100%);\r\n");
      out.write("            --gradient-sage: linear-gradient(135deg, var(--accent-sage) 0%, #9CAD7E 100%);\r\n");
      out.write("            --gradient-slate: linear-gradient(135deg, var(--accent-slate) 0%, #8F9BA8 100%);\r\n");
      out.write("            \r\n");
      out.write("            /* Shadows */\r\n");
      out.write("            --shadow-sm: 0 2px 8px rgba(109, 76, 92, 0.1);\r\n");
      out.write("            --shadow: 0 4px 20px rgba(109, 76, 92, 0.15);\r\n");
      out.write("            --shadow-lg: 0 8px 30px rgba(109, 76, 92, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        body {\r\n");
      out.write("            background-color: var(--bg-light);\r\n");
      out.write("            background-image: \r\n");
      out.write("                radial-gradient(circle at 10% 20%, var(--mauve-pastel) 0%, transparent 40%),\r\n");
      out.write("                radial-gradient(circle at 90% 10%, rgba(139, 107, 126, 0.1) 0%, transparent 40%),\r\n");
      out.write("                radial-gradient(circle at 20% 90%, rgba(201, 169, 89, 0.05) 0%, transparent 40%);\r\n");
      out.write("            background-attachment: fixed;\r\n");
      out.write("            color: var(--text-dark);\r\n");
      out.write("            font-family: 'Inter', 'Segoe UI', 'Roboto', sans-serif;\r\n");
      out.write("            font-weight: 400;\r\n");
      out.write("            line-height: 1.7;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* NAVIGATION - DARK MAUVE */\r\n");
      out.write("        .navbar {\r\n");
      out.write("            background: var(--gradient-mauve) !important;\r\n");
      out.write("            box-shadow: 0 4px 20px rgba(109, 76, 92, 0.25);\r\n");
      out.write("            border-bottom: 3px solid var(--accent-burgundy);\r\n");
      out.write("            padding: 1rem 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .navbar-brand {\r\n");
      out.write("            font-size: 1.6rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            letter-spacing: 0.5px;\r\n");
      out.write("            color: white !important;\r\n");
      out.write("            text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .navbar-nav .nav-link {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            padding: 0.5rem 1.2rem;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            margin: 0 3px;\r\n");
      out.write("            color: white !important;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .navbar-nav .nav-link:hover,\r\n");
      out.write("        .navbar-nav .nav-link.active {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);\r\n");
      out.write("            border-color: rgba(255, 255, 255, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* CARDS - PROFESSIONAL DESIGN */\r\n");
      out.write("        .card {\r\n");
      out.write("            background: var(--bg-white);\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 16px;\r\n");
      out.write("            box-shadow: var(--shadow);\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            border-top: 4px solid var(--mauve-medium);\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("            box-shadow: var(--shadow-lg);\r\n");
      out.write("            border-top-color: var(--accent-gold);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card-header {\r\n");
      out.write("            background: var(--gradient-mauve) !important;\r\n");
      out.write("            color: white !important;\r\n");
      out.write("            border-bottom: 1px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            letter-spacing: 0.3px;\r\n");
      out.write("            padding: 1.2rem 1.5rem;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* FORM ELEMENTS */\r\n");
      out.write("        .form-control, .form-select {\r\n");
      out.write("            background: var(--bg-white);\r\n");
      out.write("            border: 2px solid var(--mauve-soft);\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            padding: 0.75rem 1rem;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            color: var(--text-dark);\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-control:focus, .form-select:focus {\r\n");
      out.write("            background: var(--bg-white);\r\n");
      out.write("            border-color: var(--mauve-medium);\r\n");
      out.write("            box-shadow: 0 0 0 0.25rem rgba(139, 107, 126, 0.25);\r\n");
      out.write("            transform: translateY(-1px);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-label {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: var(--mauve-dark);\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("            letter-spacing: 0.3px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* STAR RATING - GOLD ACCENT */\r\n");
      out.write("        .rating-stars {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 12px;\r\n");
      out.write("            padding: 15px 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .star-label {\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("            color: var(--mauve-soft);\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .star-label:hover {\r\n");
      out.write("            color: var(--accent-gold);\r\n");
      out.write("            transform: scale(1.2);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .rating-stars input:checked ~ .star-label,\r\n");
      out.write("        .rating-stars input:checked ~ .star-label ~ .star-label {\r\n");
      out.write("            color: var(--accent-gold);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* BUTTONS */\r\n");
      out.write("        .btn-primary {\r\n");
      out.write("            background: var(--gradient-mauve);\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            padding: 0.75rem 2rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            letter-spacing: 0.5px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            box-shadow: 0 4px 12px rgba(109, 76, 92, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-primary:hover {\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 6px 18px rgba(109, 76, 92, 0.3);\r\n");
      out.write("            background: linear-gradient(135deg, var(--mauve-medium) 0%, var(--mauve-dark) 100%);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* INFO CARDS - DIFFERENT PROFESSIONAL COLORS */\r\n");
      out.write("        .info-card-1 {\r\n");
      out.write("            background: linear-gradient(135deg, #F8F9FA 0%, #E9ECEF 100%) !important;\r\n");
      out.write("            color: var(--text-dark);\r\n");
      out.write("            border-top: 4px solid var(--accent-sage);\r\n");
      out.write("            border-left: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .info-card-2 {\r\n");
      out.write("            background: linear-gradient(135deg, #F8F9FA 0%, #E9ECEF 100%) !important;\r\n");
      out.write("            color: var(--text-dark);\r\n");
      out.write("            border-top: 4px solid var(--accent-slate);\r\n");
      out.write("            border-left: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .info-card-3 {\r\n");
      out.write("            background: linear-gradient(135deg, #F8F9FA 0%, #E9ECEF 100%) !important;\r\n");
      out.write("            color: var(--text-dark);\r\n");
      out.write("            border-top: 4px solid var(--accent-gold);\r\n");
      out.write("            border-left: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .info-card-1 i { color: var(--accent-sage); }\r\n");
      out.write("        .info-card-2 i { color: var(--accent-slate); }\r\n");
      out.write("        .info-card-3 i { color: var(--accent-gold); }\r\n");
      out.write("        \r\n");
      out.write("        /* TOAST NOTIFICATIONS */\r\n");
      out.write("        .toast {\r\n");
      out.write("            background: var(--bg-white);\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: var(--shadow-lg);\r\n");
      out.write("            border-left: 4px solid;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .toast.success {\r\n");
      out.write("            border-left-color: var(--accent-sage);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .toast.error {\r\n");
      out.write("            border-left-color: #DC3545;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .toast-header {\r\n");
      out.write("            border-radius: 10px 10px 0 0;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* FOOTER */\r\n");
      out.write("        footer {\r\n");
      out.write("            background: linear-gradient(135deg, #343A40 0%, #495057 100%) !important;\r\n");
      out.write("            color: white;\r\n");
      out.write("            margin-top: 4rem;\r\n");
      out.write("            padding: 1.5rem 0;\r\n");
      out.write("            border-top: 3px solid var(--mauve-medium);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        footer i.fa-heart {\r\n");
      out.write("            color: var(--accent-gold);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* CUSTOM SCROLLBAR */\r\n");
      out.write("        ::-webkit-scrollbar {\r\n");
      out.write("            width: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        ::-webkit-scrollbar-track {\r\n");
      out.write("            background: var(--bg-light);\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        ::-webkit-scrollbar-thumb {\r\n");
      out.write("            background: var(--mauve-medium);\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            border: 2px solid var(--bg-light);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        ::-webkit-scrollbar-thumb:hover {\r\n");
      out.write("            background: var(--mauve-dark);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* RESPONSIVE */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .star-label {\r\n");
      out.write("                font-size: 2rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .rating-stars {\r\n");
      out.write("                gap: 8px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .btn-primary {\r\n");
      out.write("                padding: 0.6rem 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .card-header {\r\n");
      out.write("                padding: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* TEXT COLORS */\r\n");
      out.write("        .text-primary { color: var(--mauve-medium) !important; }\r\n");
      out.write("        .text-muted { color: var(--text-medium) !important; }\r\n");
      out.write("        \r\n");
      out.write("        /* BADGES */\r\n");
      out.write("        .badge {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            letter-spacing: 0.3px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .badge.bg-light {\r\n");
      out.write("            background-color: var(--mauve-pastel) !important;\r\n");
      out.write("            color: var(--mauve-dark) !important;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* ANIMATIONS */\r\n");
      out.write("        @keyframes subtleFloat {\r\n");
      out.write("            0%, 100% { transform: translateY(0); }\r\n");
      out.write("            50% { transform: translateY(-5px); }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .floating {\r\n");
      out.write("            animation: subtleFloat 3s ease-in-out infinite;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-light\">\r\n");
      out.write("    <!-- Navigation -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark shadow\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <a class=\"navbar-brand fw-bold\" href=\"index.jsp\">\r\n");
      out.write("                <i class=\"fas fa-graduation-cap me-2\"></i>Academic Feedback\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"navbar-nav ms-auto\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"admin/dashboard\">\r\n");
      out.write("                    <i class=\"fas fa-chart-line me-1\"></i>Analytics Dashboard\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- Toast Notifications -->\r\n");
      out.write("    <div class=\"toast-container position-fixed top-0 end-0 p-3\">\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Main Content -->\r\n");
      out.write("    <div class=\"container mt-5\">\r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("            <div class=\"col-lg-9 col-xl-8\">\r\n");
      out.write("                <!-- Header Card -->\r\n");
      out.write("                <div class=\"card shadow-lg border-0 mb-4\">\r\n");
      out.write("                    <div class=\"card-header text-center py-4\">\r\n");
      out.write("                        <h1 class=\"h2 fw-bold mb-3\">\r\n");
      out.write("                            <i class=\"fas fa-comment-alt me-2\"></i>Student Feedback Portal\r\n");
      out.write("                        </h1>\r\n");
      out.write("                        <p class=\"lead mb-0\">Share your academic experience to help enhance learning outcomes</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Feedback Form Card -->\r\n");
      out.write("                <div class=\"card shadow border-0 mb-4\">\r\n");
      out.write("                    <div class=\"card-body p-4\">\r\n");
      out.write("                        <form id=\"feedbackForm\" action=\"submit-feedback\" method=\"post\" novalidate>\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <!-- Student Information -->\r\n");
      out.write("                                <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                    <label for=\"studentName\" class=\"form-label\">\r\n");
      out.write("                                        <i class=\"fas fa-user me-2\"></i>Full Name *\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" id=\"studentName\" name=\"studentName\" \r\n");
      out.write("                                           value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studentName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required placeholder=\"Enter your full name\">\r\n");
      out.write("                                    <div class=\"invalid-feedback\">Please provide your name.</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                    <label for=\"studentEmail\" class=\"form-label\">\r\n");
      out.write("                                        <i class=\"fas fa-envelope me-2\"></i>Email Address *\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    <input type=\"email\" class=\"form-control\" id=\"studentEmail\" name=\"studentEmail\" \r\n");
      out.write("                                           value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studentEmail}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required placeholder=\"your.email@university.edu\">\r\n");
      out.write("                                    <div class=\"invalid-feedback\">Please provide a valid email address.</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <!-- Course & Instructor -->\r\n");
      out.write("                                <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                    <label for=\"courseName\" class=\"form-label\">\r\n");
      out.write("                                        <i class=\"fas fa-book me-2\"></i>Course Name *\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    <select class=\"form-select\" id=\"courseName\" name=\"courseName\" required>\r\n");
      out.write("                                        <option value=\"\">Select a course</option>\r\n");
      out.write("                                        <option value=\"Advanced Java Programming\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseName == 'Advanced Java Programming' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Advanced Java Programming</option>\r\n");
      out.write("                                        <option value=\"Database Management Systems\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseName == 'Database Management Systems' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Database Management Systems</option>\r\n");
      out.write("                                        <option value=\"Web Development Fundamentals\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseName == 'Web Development Fundamentals' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Web Development Fundamentals</option>\r\n");
      out.write("                                        <option value=\"Data Structures & Algorithms\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseName == 'Data Structures & Algorithms' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Data Structures & Algorithms</option>\r\n");
      out.write("                                        <option value=\"Software Engineering\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseName == 'Software Engineering' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Software Engineering</option>\r\n");
      out.write("                                        <option value=\"Machine Learning\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseName == 'Machine Learning' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Machine Learning</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                    <div class=\"invalid-feedback\">Please select a course.</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                    <label for=\"instructorName\" class=\"form-label\">\r\n");
      out.write("                                        <i class=\"fas fa-chalkboard-teacher me-2\"></i>Instructor Name *\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    <select class=\"form-select\" id=\"instructorName\" name=\"instructorName\" required>\r\n");
      out.write("                                        <option value=\"\">Select an instructor</option>\r\n");
      out.write("                                        <option value=\"Dr. Sarah Johnson\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${instructorName == 'Dr. Sarah Johnson' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Dr. Sarah Johnson</option>\r\n");
      out.write("                                        <option value=\"Prof. Michael Brown\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${instructorName == 'Prof. Michael Brown' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Prof. Michael Brown</option>\r\n");
      out.write("                                        <option value=\"Prof. Robert Davis\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${instructorName == 'Prof. Robert Davis' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Prof. Robert Davis</option>\r\n");
      out.write("                                        <option value=\"Dr. Emily Wilson\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${instructorName == 'Dr. Emily Wilson' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Dr. Emily Wilson</option>\r\n");
      out.write("                                        <option value=\"Prof. James Miller\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${instructorName == 'Prof. James Miller' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Prof. James Miller</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                    <div class=\"invalid-feedback\">Please select an instructor.</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Rating Section -->\r\n");
      out.write("                            <div class=\"mb-4\">\r\n");
      out.write("                                <label class=\"form-label d-block text-center mb-3\">\r\n");
      out.write("                                    <i class=\"fas fa-star me-2\"></i>Course Rating *\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <div class=\"rating-container\">\r\n");
      out.write("                                    <div class=\"rating-stars mb-2\">\r\n");
      out.write("                                        <input type=\"radio\" id=\"star5\" name=\"rating\" value=\"5\" class=\"d-none\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.rating == '5' ? 'checked' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("                                        <label for=\"star5\" class=\"star-label\"><i class=\"fas fa-star\"></i></label>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <input type=\"radio\" id=\"star4\" name=\"rating\" value=\"4\" class=\"d-none\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.rating == '4' ? 'checked' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("                                        <label for=\"star4\" class=\"star-label\"><i class=\"fas fa-star\"></i></label>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <input type=\"radio\" id=\"star3\" name=\"rating\" value=\"3\" class=\"d-none\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.rating == '3' ? 'checked' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("                                        <label for=\"star3\" class=\"star-label\"><i class=\"fas fa-star\"></i></label>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <input type=\"radio\" id=\"star2\" name=\"rating\" value=\"2\" class=\"d-none\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.rating == '2' ? 'checked' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("                                        <label for=\"star2\" class=\"star-label\"><i class=\"fas fa-star\"></i></label>\r\n");
      out.write("                                        \r\n");
      out.write("                                        <input type=\"radio\" id=\"star1\" name=\"rating\" value=\"1\" class=\"d-none\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.rating == '1' ? 'checked' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("                                        <label for=\"star1\" class=\"star-label\"><i class=\"fas fa-star\"></i></label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"text-center\">\r\n");
      out.write("                                        <small class=\"text-muted d-block mb-1\">Rate from 1 (Poor) to 5 (Excellent)</small>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"invalid-feedback d-block text-center mt-1\">Please select a rating.</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Comments -->\r\n");
      out.write("                            <div class=\"mb-4\">\r\n");
      out.write("                                <label for=\"comments\" class=\"form-label\">\r\n");
      out.write("                                    <i class=\"fas fa-comment me-2\"></i>Additional Comments\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <textarea class=\"form-control\" id=\"comments\" name=\"comments\" rows=\"4\" \r\n");
      out.write("                                          placeholder=\"Share constructive feedback about the course content, teaching methods, or suggestions for improvement...\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comments}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("                                <div class=\"form-text\">\r\n");
      out.write("                                    <i class=\"fas fa-info-circle me-1\"></i> Specific, constructive feedback is most valuable\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Submit Button -->\r\n");
      out.write("                            <div class=\"text-center pt-2\">\r\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-primary btn-lg px-4\">\r\n");
      out.write("                                    <i class=\"fas fa-paper-plane me-2\"></i>Submit Feedback\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Info Cards -->\r\n");
      out.write("                <div class=\"row mt-4\">\r\n");
      out.write("                    <div class=\"col-md-4 mb-3\">\r\n");
      out.write("                        <div class=\"card info-card-1 text-center border-0 shadow\">\r\n");
      out.write("                            <div class=\"card-body py-3\">\r\n");
      out.write("                                <i class=\"fas fa-user-shield fa-2x mb-2\"></i>\r\n");
      out.write("                                <h6 class=\"card-title fw-bold mb-2\">Confidential</h6>\r\n");
      out.write("                                <p class=\"card-text small mb-0\">All feedback is anonymous and confidential</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 mb-3\">\r\n");
      out.write("                        <div class=\"card info-card-2 text-center border-0 shadow\">\r\n");
      out.write("                            <div class=\"card-body py-3\">\r\n");
      out.write("                                <i class=\"fas fa-chart-bar fa-2x mb-2\"></i>\r\n");
      out.write("                                <h6 class=\"card-title fw-bold mb-2\">Impactful</h6>\r\n");
      out.write("                                <p class=\"card-text small mb-0\">Drives meaningful curriculum improvements</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 mb-3\">\r\n");
      out.write("                        <div class=\"card info-card-3 text-center border-0 shadow\">\r\n");
      out.write("                            <div class=\"card-body py-3\">\r\n");
      out.write("                                <i class=\"fas fa-handshake fa-2x mb-2\"></i>\r\n");
      out.write("                                <h6 class=\"card-title fw-bold mb-2\">Collaborative</h6>\r\n");
      out.write("                                <p class=\"card-text small mb-0\">Enhances the teaching-learning partnership</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <footer class=\"text-white text-center py-4 mt-4\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <p class=\"mb-2\">&copy; 2024 Academic Feedback System. All rights reserved.</p>\r\n");
      out.write("            <small class=\"text-light\">Designed to enhance educational excellence</small>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <!-- Scripts -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"js/script.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("        // Star rating functionality\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("            const stars = document.querySelectorAll('.star-label');\r\n");
      out.write("            \r\n");
      out.write("            stars.forEach(star => {\r\n");
      out.write("                star.addEventListener('click', function() {\r\n");
      out.write("                    const rating = this.previousElementSibling.value;\r\n");
      out.write("                    highlightStars(rating);\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                star.addEventListener('mouseover', function() {\r\n");
      out.write("                    const rating = this.previousElementSibling.value;\r\n");
      out.write("                    previewStars(rating);\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            function highlightStars(rating) {\r\n");
      out.write("                stars.forEach((star, index) => {\r\n");
      out.write("                    if (index < 5 - rating) {\r\n");
      out.write("                        star.style.color = '#D1C2C9';\r\n");
      out.write("                    } else {\r\n");
      out.write("                        star.style.color = '#C9A959';\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            function previewStars(rating) {\r\n");
      out.write("                stars.forEach((star, index) => {\r\n");
      out.write("                    if (index < 5 - rating) {\r\n");
      out.write("                        star.style.color = '#D1C2C9';\r\n");
      out.write("                    } else {\r\n");
      out.write("                        star.style.color = '#D4B483';\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            // Initialize with checked star if exists\r\n");
      out.write("            const checkedStar = document.querySelector('.rating-stars input:checked');\r\n");
      out.write("            if (checkedStar) {\r\n");
      out.write("                highlightStars(checkedStar.value);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /index.jsp(337,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty successMessage}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("            <div class=\"toast show success\" role=\"alert\">\r\n");
        out.write("                <div class=\"toast-header\" style=\"background: linear-gradient(to right, var(--accent-sage), #9CAD7E); color: white;\">\r\n");
        out.write("                    <i class=\"fas fa-check-circle me-2\"></i>\r\n");
        out.write("                    <strong class=\"me-auto\">Success</strong>\r\n");
        out.write("                    <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"toast\"></button>\r\n");
        out.write("                </div>\r\n");
        out.write("                <div class=\"toast-body\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${successMessage}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</div>\r\n");
        out.write("            </div>\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /index.jsp(348,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty errorMessage}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("            <div class=\"toast show error\" role=\"alert\">\r\n");
        out.write("                <div class=\"toast-header\" style=\"background: linear-gradient(to right, #DC3545, #C82333); color: white;\">\r\n");
        out.write("                    <i class=\"fas fa-exclamation-circle me-2\"></i>\r\n");
        out.write("                    <strong class=\"me-auto\">Error</strong>\r\n");
        out.write("                    <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"toast\"></button>\r\n");
        out.write("                </div>\r\n");
        out.write("                <div class=\"toast-body\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMessage}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</div>\r\n");
        out.write("            </div>\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
